# Site Info
title:              Heygwangjin 
tagline:            'slowly but steadily' 
url:                http://heygwangjin.github.io
baseurl:            ""

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name:             Gwangjin Kim
  description:      Hi! I am learning about computer science in Ajou University which is located in Suwon of South Korea.
  gravatar:         345282cea9b5ee8608aa1c865f21df72 # md5 hash of your email address 
  contact:
    instagram:      https://www.instagram.com/pangj1n/ 
    github:         https://github.com/heygwangjin
    email:          mailto:cer3@ajou.ac.kr 
    # linkedin:     <hide>
    # facebook:     <hide>

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Today I Learned:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - '/myself/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/background.png
  caption: Thank you for visiting my website<br>You can see my posting by cliking the menu button on the top right.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'G-ST0W38E98W' # leave blank if you don't want google analytics
disqus_short_name: 'heygwangjin' # leave blank if you don't want disqus

